---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Description: Creating an S3 bucket for storing CFN templates
    Type: String

Resources:
  S3Bucket:                                                                                 
    Type: AWS::S3::Bucket                                                                   
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
    DeletionPolicy: Retain

  BucketPolicy:                                                                             
    Type: AWS::S3::BucketPolicy                                                             
    Properties:                                                                             
      PolicyDocument:                                                                       
        Id: TCS3Policy                                                                      
        Version: 2012-10-17                                                                 
        Statement:                                                                          
          - Sid: PublicReadForGetBucketObjects                                              
            Effect: Allow                                                                   
            Principal: '*'                                                                  
            Action: 's3:GetObject'                                                          
            Resource: !Join                                                                 
              - ''                                                                          
              - - 'arn:aws:s3:::'                                                           
                - !Ref S3Bucket                                                             
                - /*                                                                        
      Bucket: !Ref S3Bucket    
